name: Update documentation

on:
  push:
    branches:
      - "master"
    paths:
      - "docs/**"
      - "include/MyGL/**.hpp"

jobs:
  documentation:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install the dependencies
        run: |
          sudo apt install -y ninja doxygen
          sudo pip3 install meson

      - name: Configure meson
        run: |
          meson wrap update-db 
          meson setup build -Dmygl_build_doc=true --prefix=${{github.workspace}}/install

      - name: Generate the documentation pages
        working-directory: ${{github.workspace}}/build
        run: |
          meson compile docs/docs
          meson install

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          publish_dir: ${{github.workspace}}/install/share/MyGL/html
          enable_jekyll: false
          allow_empty_commit: false
