name: Update documentation

on:
  push:
    branches:
      - master
    paths:
      - docs/**
      - include/MyGL/**.hpp
      - .github/workflows/update_docs.yml

jobs:
  documentation:
    runs-on: ubuntu-latest

    env:
      doxygen-version: "1.10.0"
    
    steps:
      - uses: actions/checkout@v4

      - name: Cache Doxygen
        id: cache-doxygen
        uses: actions/cache@v3
        with:
          path: ~/.local/bin/doxygen
          key: doxygen-${{ runner.os }}-${{ env.doxygen-version }}

      - if: ${{ steps.cache-doxygen.outputs.cache-hit != 'true' }}
        working-directory: ${{ runner.temp }}
        name: Install Doxygen
        run: |
          wget https://www.doxygen.nl/files/doxygen-${{ env.doxygen-version }}.linux.bin.tar.gz
          tar xf doxygen-${{ env.doxygen-version }}.linux.bin.tar.gz
          mv doxygen-${{ env.doxygen-version }}/bin/doxygen ~/.local/bin/

      - name: Install the dependencies
        run: |
          sudo apt install -y ninja-build
          sudo pip3 install meson
          echo ~/.local/bin >> $GITHUB_PATH

      - name: Configure meson
        run: meson setup build --prefix=${{github.workspace}}/install -Dmygl_docs_only=true

      - name: Generate the documentation pages
        working-directory: ${{github.workspace}}/build
        run: |
          meson compile docs/docs
          meson install

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          publish_dir: ${{github.workspace}}/install/share/MyGL/html
          enable_jekyll: false
          allow_empty_commit: false
